#!/bin/bash
# My first script

datafile=$1
matlab -nodesktop -nosplash -r "data_file='$datafile';analyse_data;exit"
pdflatex "\def\myvar{$datafile} \input{figures.tex}"
pdflatex "\def\myvar{$datafile} \input{figures_log.tex}"
pdflatex "\def\myvar{$datafile} \input{regression_plot.tex}"

