#!/bin/bash
# bash script to generate significant plots

datafile=$1
windowsize=$2
matlab -nodesktop -nosplash -r "data_file='$datafile';window_size=$windowsize;analyse_data;exit"
#pdflatex "\def\myvar{$datafile} \def\window{$windowsize} \input{figures.tex}"
#pdflatex "\def\myvar{$datafile} \def\window{$windowsize} \input{figures_log.tex}"
#pdflatex "\def\myvar{$datafile} \def\window{$windowsize} \input{regression_plot.tex}"

