%Name:feature_channel_creator
%By: Leon. F. Palafox
%Description: This script runs after iterator_script.m, since it need the
%variable generated by it.
%This generate a set of files that contain either a single channel's single
%band information or you can add the label information for each time point
%in the series.
%The need for the labels comes from the python script that will run them.
%First define how many frequency bands you want to analyze
labels_flag = 1;
bands = {}; %Define a cell array for the bands
%Define the specific bands to analyze by defining variables as band
%Store the bands
bands{1} = [12:32]; %beta band
bands{2} = [72:92]; %gamma band
%Create a directory that will contain all of the datasets
dir_name = 'EEGDatasets';
%check if it exists
if exist(dir_name, 'dir') == 7
     s_in = input('There is a working directory already in file, do you want to overwrite it? [y/n]', 's');
     if s_in == 'y'
         rmdir(dir_name, 's');
         disp(['Creating Directory ' dir_name])
         mkdir(dir_name)
     else
         break
     end
else
    disp(['Creating Directory ' dir_name])
    mkdir(dir_name)
end
%Create a metadata file that contains information regarding the datasets
create_metadata(bands, fourier_sampling_rate, dir_name)
%iterate over bands to create the different datasets
for band_idx = 1:length(bands)
    %first we need to create the band directory under the main directory
    band_dir = [dir_name '/band_' num2str(band_idx)];
    mkdir(band_dir)
    for chan_idx = 1:get_variables('number_of_channels') %go over every channel
        [dataset, labels_dataset] = extract_data(large_power_matrix, large_labels, 'rise', fourier_sampling_rate, F, bands{band_idx}, chan_idx);
        file_name = ['channel_' num2str(chan_idx) '.nspd'];
        if labels_flag == 0 %if you do not want the labels
            csvwrite(fullfile(band_dir, file_name), [dataset])
        else %if you want the labels
            csvwrite(fullfile(band_dir, file_name), [dataset labels_dataset])
        end
    end
end
    
