#############################################################################
# Generated by PAGE version 4.2.3
# in conjunction with Tcl version 8.6
#    Apr. 21, 2014 09:59:52 AM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#############################################################################
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {DejaVu Sans} -size -12 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top34
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    set site_4_0 .top34.tNo35.pg0 
    set site_4_0 $site_4_0
    set site_4_1 .top34.tNo35.pg1 
    set site_4_0 $site_4_1
    set site_4_2 .top34.tNo35.pg2 
    set site_4_0 $site_4_2
    set site_4_3 .top34.tNo35.pg3 
    set site_4_0 $site_4_3
    set site_5_0 $site_4_0.tLa73
    set site_7_0 .top34.tNo35.pg3.tLa73.tNo82.pg0 
    set site_7_0 $site_7_0
    set site_7_1 .top34.tNo35.pg3.tLa73.tNo82.pg1 
    set site_7_0 $site_7_1
    set site_7_2 .top34.tNo35.pg3.tLa73.tNo82.pg2 
    set site_7_0 $site_7_2
    set site_5_0 $site_4_0.tLa107
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 1x1+0+0; update
    wm maxsize $top 1905 1170
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page.tcl"
    bindtags $top "$top Page.tcl all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top34 {base} {
    if {$base == ""} {
        set base .top34
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -menu "$top.m116" -relief sunken -background {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 624x557+780+474; update
    wm maxsize $top 624 557
    wm minsize $top 624 557
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Launcher"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    bindtags $top "$top Toplevel all _TopLevel"
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook -foreground #000000
    ttk::style configure TNotebook -font TkDefaultFont
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo35 \
        -width 602 -height 474 -takefocus {} 
    vTcl:DefineAlias "$top.tNo35" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame .top34.tNo35.pg0 -background #d9d9d9
    $top.tNo35 add .top34.tNo35.pg0 \
        -padding 0 -sticky nsew -state normal -text Subject -image {} \
        -compound none -underline -1 
    set site_4_0  $top.tNo35.pg0
    label $site_4_0.lab36 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Age: 
    vTcl:DefineAlias "$site_4_0.lab36" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent38 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -textvariable age 
    vTcl:DefineAlias "$site_4_0.ent38" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad39 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -cursor hand1 -foreground {#000000} \
        -highlightcolor black -text Male -value Male -variable gender 
    vTcl:DefineAlias "$site_4_0.rad39" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad45 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -cursor hand1 -foreground {#000000} \
        -highlightcolor black -text Female -value Female -variable gender 
    vTcl:DefineAlias "$site_4_0.rad45" "Radiobutton2" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab34 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Sex: 
    vTcl:DefineAlias "$site_4_0.lab34" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab35 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Subject Number:} 
    vTcl:DefineAlias "$site_4_0.lab35" "Label3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent36 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable subjectNumber 
    vTcl:DefineAlias "$site_4_0.ent36" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab37 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Hand Dominance:} 
    vTcl:DefineAlias "$site_4_0.lab37" "Label4" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad38 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -cursor hand1 -foreground {#000000} \
        -highlightcolor black -text Right-handed -value Right-handed \
        -variable hand 
    vTcl:DefineAlias "$site_4_0.rad38" "Radiobutton3" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad40 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -cursor hand1 -foreground {#000000} \
        -highlightcolor black -text Left-handed -value Left-handed \
        -variable hand 
    vTcl:DefineAlias "$site_4_0.rad40" "Radiobutton4" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Grid Hemisphere:} 
    vTcl:DefineAlias "$site_4_0.lab41" "Label5" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_4_0.che118 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Right -variable gridHemisphereRight 
    vTcl:DefineAlias "$site_4_0.che118" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_4_0.che119 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Left -variable gridHemisphereLeft 
    vTcl:DefineAlias "$site_4_0.che119" "Checkbutton2" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab36 \
        -in $site_4_0 -x 200 -y 20 -anchor nw -bordermode ignore 
    place $site_4_0.ent38 \
        -in $site_4_0 -x 250 -y 20 -width 56 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.rad39 \
        -in $site_4_0 -x 240 -y 60 -anchor nw -bordermode ignore 
    place $site_4_0.rad45 \
        -in $site_4_0 -x 240 -y 80 -anchor nw -bordermode ignore 
    place $site_4_0.lab34 \
        -in $site_4_0 -x 200 -y 60 -anchor nw -bordermode ignore 
    place $site_4_0.lab35 \
        -in $site_4_0 -x 130 -y 120 -anchor nw -bordermode ignore 
    place $site_4_0.ent36 \
        -in $site_4_0 -x 250 -y 120 -width 56 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab37 \
        -in $site_4_0 -x 120 -y 160 -anchor nw -bordermode ignore 
    place $site_4_0.rad38 \
        -in $site_4_0 -x 240 -y 160 -anchor nw -bordermode ignore 
    place $site_4_0.rad40 \
        -in $site_4_0 -x 240 -y 180 -anchor nw -bordermode ignore 
    place $site_4_0.lab41 \
        -in $site_4_0 -x 120 -y 220 -anchor nw -bordermode ignore 
    place $site_4_0.che118 \
        -in $site_4_0 -x 240 -y 240 -anchor nw -bordermode ignore 
    place $site_4_0.che119 \
        -in $site_4_0 -x 240 -y 220 -anchor nw -bordermode ignore 
    frame .top34.tNo35.pg1 -background #d9d9d9
    $top.tNo35 add .top34.tNo35.pg1 \
        -padding 0 -sticky nsew -state normal -text {Data Acquisition} \
        -image {} -compound none -underline -1 
    set site_4_1  $top.tNo35.pg1
    label $site_4_1.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Machine being used:} 
    vTcl:DefineAlias "$site_4_1.lab45" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_1.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Sampling rate:} 
    vTcl:DefineAlias "$site_4_1.lab46" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_1.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {ECoG channels:} 
    vTcl:DefineAlias "$site_4_1.lab47" "Label8" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_1.tCo48 \
        -values {TDT gHIamp} -textvariable machineBeingUsed -foreground {} \
        -background {} -takefocus {} -cursor hand1 
    vTcl:DefineAlias "$site_4_1.tCo48" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_1.tCo49 \
        -textvariable samplingRate -foreground {} -background {} \
        -takefocus {} -cursor hand1 
    vTcl:DefineAlias "$site_4_1.tCo49" "TCombobox2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_1.ent50 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable ecogChannels 
    vTcl:DefineAlias "$site_4_1.ent50" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_1.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Force sensor channel:} 
    vTcl:DefineAlias "$site_4_1.lab51" "Label9" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_1.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {EMG channels:} 
    vTcl:DefineAlias "$site_4_1.lab52" "Label10" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_1.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Synchronizing pulse channel:} 
    vTcl:DefineAlias "$site_4_1.lab53" "Label11" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_1.ent54 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable forceSensorChannel 
    vTcl:DefineAlias "$site_4_1.ent54" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_1.ent55 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable emgChannels 
    vTcl:DefineAlias "$site_4_1.ent55" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_1.ent56 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable synchronizingPulseChannel 
    vTcl:DefineAlias "$site_4_1.ent56" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_1.lab45 \
        -in $site_4_1 -x 130 -y 30 -anchor nw -bordermode ignore 
    place $site_4_1.lab46 \
        -in $site_4_1 -x 160 -y 70 -anchor nw -bordermode ignore 
    place $site_4_1.lab47 \
        -in $site_4_1 -x 150 -y 110 -width 108 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tCo48 \
        -in $site_4_1 -x 270 -y 30 -width 127 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_1.tCo49 \
        -in $site_4_1 -x 270 -y 70 -width 87 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_1.ent50 \
        -in $site_4_1 -x 270 -y 110 -width 146 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_1.lab51 \
        -in $site_4_1 -x 110 -y 150 -anchor nw -bordermode ignore 
    place $site_4_1.lab52 \
        -in $site_4_1 -x 150 -y 190 -width 103 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_1.lab53 \
        -in $site_4_1 -x 70 -y 230 -anchor nw -bordermode ignore 
    place $site_4_1.ent54 \
        -in $site_4_1 -x 270 -y 150 -width 46 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_1.ent55 \
        -in $site_4_1 -x 270 -y 190 -anchor nw -bordermode ignore 
    place $site_4_1.ent56 \
        -in $site_4_1 -x 270 -y 230 -width 46 -height 21 -anchor nw \
        -bordermode ignore 
    frame .top34.tNo35.pg2 -background #d9d9d9
    $top.tNo35 add .top34.tNo35.pg2 \
        -padding 0 -sticky nsew -state normal -text {Squeeze Task} -image {} \
        -compound none -underline -1 
    set site_4_2  $top.tNo35.pg2
    button $site_4_2.but60 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -command StopSqueezeTask -cursor hand1 \
        -foreground {#000000} -highlightcolor black -text {Stop Squeeze Task} \
        -wraplength 100 
    vTcl:DefineAlias "$site_4_2.but60" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_2.but61 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -command RunDemoSqueeze -cursor hand1 \
        -foreground {#000000} -highlightcolor black \
        -text {Run Demo Squeeze Task} -wraplength 100 
    vTcl:DefineAlias "$site_4_2.but61" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_2.but62 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -command RunSqueeze -cursor hand1 \
        -foreground {#000000} -highlightcolor black -text {Run Squeeze Task} 
    vTcl:DefineAlias "$site_4_2.but62" "Button3" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_2.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Force sensor is in patient's:} 
    vTcl:DefineAlias "$site_4_2.lab63" "Label12" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_2.rad64 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -cursor hand1 -foreground {#000000} \
        -highlightcolor black -text {Right Hand} -value {Right Hand} \
        -variable sensorHand 
    vTcl:DefineAlias "$site_4_2.rad64" "Radiobutton8" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_2.rad35 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Left Hand} -value {Left hand} -variable sensorHand 
    vTcl:DefineAlias "$site_4_2.rad35" "Radiobutton5" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_2.but60 \
        -in $site_4_2 -x 330 -y 170 -width 117 -height 97 -anchor nw \
        -bordermode ignore 
    place $site_4_2.but61 \
        -in $site_4_2 -x 190 -y 170 -width 127 -height 57 -anchor nw \
        -bordermode ignore 
    place $site_4_2.but62 \
        -in $site_4_2 -x 190 -y 230 -width 127 -height 37 -anchor nw \
        -bordermode ignore 
    place $site_4_2.lab63 \
        -in $site_4_2 -x 130 -y 50 -anchor nw -bordermode ignore 
    place $site_4_2.rad64 \
        -in $site_4_2 -x 300 -y 50 -anchor nw -bordermode ignore 
    place $site_4_2.rad35 \
        -in $site_4_2 -x 300 -y 70 -anchor nw -bordermode ignore 
    frame .top34.tNo35.pg3 -background #d9d9d9
    $top.tNo35 add .top34.tNo35.pg3 \
        -padding 0 -sticky nsew -state normal -text {BCI Task} -image {} \
        -compound none -underline -1 
    set site_4_3  $top.tNo35.pg3
    button $site_4_3.cpd66 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -command StopBCITask -cursor hand1 \
        -foreground {#000000} -highlightcolor black -text {Stop BCI Task} \
        -wraplength 100 
    vTcl:DefineAlias "$site_4_3.cpd66" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_3.but67 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -command StartDemoBCI -cursor hand1 \
        -foreground {#000000} -highlightcolor black \
        -text {Start Demo BCI Task (data is not written to file)} \
        -wraplength 100 
    vTcl:DefineAlias "$site_4_3.but67" "Button5" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_3.but68 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -command RunBCI -cursor hand1 \
        -foreground {#000000} -highlightcolor black -text {Run BCI Task} 
    vTcl:DefineAlias "$site_4_3.but68" "Button6" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_3.tLa73 \
        -text Algorithm -width 580 -height 225 
    vTcl:DefineAlias "$site_4_3.tLa73" "TLabelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_3.tLa73
    ttk::combobox $site_5_0.tCo74 \
        -values {"Running Average" "Training JointRSE" "Testing JointRSE"} \
        -textvariable algorithm -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo74" "TCombobox4" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.cpd75 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {BCI Algorithm being used:} 
    vTcl:DefineAlias "$site_5_0.cpd75" "Label13" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $site_5_0.tNo82 \
        -width 562 -height 164 -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tNo82" "TNotebook2" vTcl:WidgetProc "Toplevel1" 1
    frame .top34.tNo35.pg3.tLa73.tNo82.pg0 -background #d9d9d9
    $site_5_0.tNo82 add .top34.tNo35.pg3.tLa73.tNo82.pg0 \
        -padding 0 -sticky nsew -state normal -text {Moving Average} \
        -image {} -compound none -underline -1 
    set site_7_0  $site_5_0.tNo82.pg0
    label $site_7_0.cpd83 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {x-axis channels (multiple channels are averaged):} 
    vTcl:DefineAlias "$site_7_0.cpd83" "Label19" vTcl:WidgetProc "Toplevel1" 1
    label $site_7_0.cpd84 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {x-axis frequencies (multiple frequencies are avergaed):} 
    vTcl:DefineAlias "$site_7_0.cpd84" "Label14" vTcl:WidgetProc "Toplevel1" 1
    label $site_7_0.cpd85 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {y-axis channels (multiple channels are averaged):} 
    vTcl:DefineAlias "$site_7_0.cpd85" "Label15" vTcl:WidgetProc "Toplevel1" 1
    label $site_7_0.cpd86 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {y-axis frequencies (multiple frequencies are avergaed):} 
    vTcl:DefineAlias "$site_7_0.cpd86" "Label16" vTcl:WidgetProc "Toplevel1" 1
    label $site_7_0.cpd87 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {z-axis channels (multiple channels are averaged):} 
    vTcl:DefineAlias "$site_7_0.cpd87" "Label17" vTcl:WidgetProc "Toplevel1" 1
    label $site_7_0.cpd88 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {z-axis frequencies (multiple frequencies are avergaed):} 
    vTcl:DefineAlias "$site_7_0.cpd88" "Label18" vTcl:WidgetProc "Toplevel1" 1
    entry $site_7_0.ent89 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable bciMovingaverageXChannels 
    vTcl:DefineAlias "$site_7_0.ent89" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    entry $site_7_0.ent90 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable bciMovingaverageXFrequencies 
    vTcl:DefineAlias "$site_7_0.ent90" "Entry8" vTcl:WidgetProc "Toplevel1" 1
    entry $site_7_0.ent91 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable bciMovingaverageYChannels 
    vTcl:DefineAlias "$site_7_0.ent91" "Entry9" vTcl:WidgetProc "Toplevel1" 1
    entry $site_7_0.ent92 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable bciMovingaverageYChannels 
    vTcl:DefineAlias "$site_7_0.ent92" "Entry10" vTcl:WidgetProc "Toplevel1" 1
    entry $site_7_0.ent93 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable bciMovingaverageZChannels 
    vTcl:DefineAlias "$site_7_0.ent93" "Entry11" vTcl:WidgetProc "Toplevel1" 1
    entry $site_7_0.ent94 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable bciMovingaverageZFrequencies 
    vTcl:DefineAlias "$site_7_0.ent94" "Entry12" vTcl:WidgetProc "Toplevel1" 1
    place $site_7_0.cpd83 \
        -in $site_7_0 -x 10 -y 10 -anchor nw -bordermode inside 
    place $site_7_0.cpd84 \
        -in $site_7_0 -x 10 -y 30 -width 336 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_7_0.cpd85 \
        -in $site_7_0 -x 10 -y 50 -anchor nw -bordermode inside 
    place $site_7_0.cpd86 \
        -in $site_7_0 -x 10 -y 70 -anchor nw -bordermode inside 
    place $site_7_0.cpd87 \
        -in $site_7_0 -x 10 -y 90 -anchor nw -bordermode inside 
    place $site_7_0.cpd88 \
        -in $site_7_0 -x 10 -y 110 -anchor nw -bordermode inside 
    place $site_7_0.ent89 \
        -in $site_7_0 -x 380 -y 10 -anchor nw -bordermode ignore 
    place $site_7_0.ent90 \
        -in $site_7_0 -x 380 -y 30 -anchor nw -bordermode ignore 
    place $site_7_0.ent91 \
        -in $site_7_0 -x 380 -y 50 -anchor nw -bordermode ignore 
    place $site_7_0.ent92 \
        -in $site_7_0 -x 380 -y 70 -anchor nw -bordermode ignore 
    place $site_7_0.ent93 \
        -in $site_7_0 -x 380 -y 90 -anchor nw -bordermode ignore 
    place $site_7_0.ent94 \
        -in $site_7_0 -x 380 -y 110 -anchor nw -bordermode ignore 
    frame .top34.tNo35.pg3.tLa73.tNo82.pg1 -background #d9d9d9
    $site_5_0.tNo82 add .top34.tNo35.pg3.tLa73.tNo82.pg1 \
        -padding 0 -sticky nsew -state normal -text JointRSE -image {} \
        -compound none -underline -1 
    set site_7_1  $site_5_0.tNo82.pg1
    label $site_7_1.lab95 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Channels used by BCI (multiple channels are not averaged):} 
    vTcl:DefineAlias "$site_7_1.lab95" "Label20" vTcl:WidgetProc "Toplevel1" 1
    label $site_7_1.lab96 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Frequencies used by BCI (multiple frequencies are separate features):} 
    vTcl:DefineAlias "$site_7_1.lab96" "Label21" vTcl:WidgetProc "Toplevel1" 1
    entry $site_7_1.ent97 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable bciJointrseChannels 
    vTcl:DefineAlias "$site_7_1.ent97" "Entry13" vTcl:WidgetProc "Toplevel1" 1
    entry $site_7_1.ent98 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable bciJointrseFrequencies 
    vTcl:DefineAlias "$site_7_1.ent98" "Entry14" vTcl:WidgetProc "Toplevel1" 1
    place $site_7_1.lab95 \
        -in $site_7_1 -x 10 -y 10 -width 367 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_7_1.lab96 \
        -in $site_7_1 -x 10 -y 70 -anchor nw -bordermode ignore 
    place $site_7_1.ent97 \
        -in $site_7_1 -x 280 -y 40 -width 266 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_7_1.ent98 \
        -in $site_7_1 -x 280 -y 100 -width 266 -height 21 -anchor nw \
        -bordermode ignore 
    frame .top34.tNo35.pg3.tLa73.tNo82.pg2 -background #d9d9d9
    $site_5_0.tNo82 add .top34.tNo35.pg3.tLa73.tNo82.pg2 \
        -padding 0 -sticky nsew -state normal -text {Real-time PSD} -image {} \
        -compound none -underline -1 
    set site_7_2  $site_5_0.tNo82.pg2
    label $site_7_2.lab99 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Window type:} 
    vTcl:DefineAlias "$site_7_2.lab99" "Label22" vTcl:WidgetProc "Toplevel1" 1
    label $site_7_2.lab100 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Window rate:} 
    vTcl:DefineAlias "$site_7_2.lab100" "Label23" vTcl:WidgetProc "Toplevel1" 1
    label $site_7_2.lab101 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Window length:} 
    vTcl:DefineAlias "$site_7_2.lab101" "Label24" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_7_2.tCo102 \
        -values {"Rectangle" "Hamming" "Blackman-Harris"} \
        -textvariable psdWindowType -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_7_2.tCo102" "TCombobox3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_7_2.ent103 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable psdFeatureRate 
    vTcl:DefineAlias "$site_7_2.ent103" "Entry15" vTcl:WidgetProc "Toplevel1" 1
    label $site_7_2.lab104 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Hz 
    vTcl:DefineAlias "$site_7_2.lab104" "Label25" vTcl:WidgetProc "Toplevel1" 1
    entry $site_7_2.ent105 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable psdWindowLength 
    vTcl:DefineAlias "$site_7_2.ent105" "Entry16" vTcl:WidgetProc "Toplevel1" 1
    label $site_7_2.lab106 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text seconds 
    vTcl:DefineAlias "$site_7_2.lab106" "Label26" vTcl:WidgetProc "Toplevel1" 1
    place $site_7_2.lab99 \
        -in $site_7_2 -x 120 -y 20 -anchor nw -bordermode ignore 
    place $site_7_2.lab100 \
        -in $site_7_2 -x 120 -y 50 -anchor nw -bordermode ignore 
    place $site_7_2.lab101 \
        -in $site_7_2 -x 100 -y 80 -width 109 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_7_2.tCo102 \
        -in $site_7_2 -x 220 -y 20 -width 167 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_7_2.ent103 \
        -in $site_7_2 -x 220 -y 50 -width 76 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_7_2.lab104 \
        -in $site_7_2 -x 300 -y 50 -anchor nw -bordermode ignore 
    place $site_7_2.ent105 \
        -in $site_7_2 -x 220 -y 80 -width 76 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_7_2.lab106 \
        -in $site_7_2 -x 300 -y 80 -anchor nw -bordermode ignore 
    place $site_5_0.tCo74 \
        -in $site_5_0 -x 280 -y 20 -width 177 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.cpd75 \
        -in $site_5_0 -x 110 -y 0 -anchor nw -bordermode inside 
    place $site_5_0.tNo82 \
        -in $site_5_0 -x 10 -y 50 -width 562 -height 164 -anchor nw \
        -bordermode ignore 
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_3.tLa107 \
        -text {Virtual Environment} -width 580 -height 115 
    vTcl:DefineAlias "$site_4_3.tLa107" "TLabelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_3.tLa107
    label $site_5_0.lab108 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Game: 
    vTcl:DefineAlias "$site_5_0.lab108" "Label27" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo109 \
        -values {"BCI Hero"} -textvariable game -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo109" "TCombobox5" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab110 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Workspace Dimension:} 
    vTcl:DefineAlias "$site_5_0.lab110" "Label28" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo111 \
        -values {"1D" "2D-xy" "2D-xz"} -textvariable workspace -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo111" "TCombobox6" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab112 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Target Bar width percent of screen:} 
    vTcl:DefineAlias "$site_5_0.lab112" "Label29" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab113 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Target Bar Length in seconds:} 
    vTcl:DefineAlias "$site_5_0.lab113" "Label30" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent114 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable barWidth 
    vTcl:DefineAlias "$site_5_0.ent114" "Entry17" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent115 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable barLength 
    vTcl:DefineAlias "$site_5_0.ent115" "Entry18" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab108 \
        -in $site_5_0 -x 180 -y 20 -width 43 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tCo109 \
        -in $site_5_0 -x 250 -y 20 -anchor nw -bordermode ignore 
    place $site_5_0.lab110 \
        -in $site_5_0 -x 90 -y 40 -anchor nw -bordermode ignore 
    place $site_5_0.tCo111 \
        -in $site_5_0 -x 250 -y 43 -width 177 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab112 \
        -in $site_5_0 -x 10 -y 70 -anchor nw -bordermode ignore 
    place $site_5_0.lab113 \
        -in $site_5_0 -x 40 -y 90 -anchor nw -bordermode ignore 
    place $site_5_0.ent114 \
        -in $site_5_0 -x 250 -y 68 -width 56 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent115 \
        -in $site_5_0 -x 250 -y 88 -width 56 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_3.cpd66 \
        -in $site_4_3 -x 340 -y 350 -width 132 -height 97 -anchor nw \
        -bordermode ignore 
    place $site_4_3.but67 \
        -in $site_4_3 -x 180 -y 350 -width 147 -height 67 -anchor nw \
        -bordermode ignore 
    place $site_4_3.but68 \
        -in $site_4_3 -x 180 -y 420 -width 147 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_3.tLa73 \
        -in $site_4_3 -x 10 -y 3 -width 580 -height 225 -anchor nw \
        -bordermode ignore 
    place $site_4_3.tLa107 \
        -in $site_4_3 -x 10 -y 231 -width 580 -height 115 -anchor nw \
        -bordermode ignore 
    menu $top.m116 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    label $top.lab42 \
        -activebackground {#ed0707} -activeforeground black \
        -background {#ff3030} -disabledforeground {#a30000} -font font10 \
        -foreground {#000000} -highlightbackground {#d80000} \
        -highlightcolor black \
        -text {Not streaming from data acquisition system} \
        -textvariable streamingState 
    vTcl:DefineAlias "$top.lab42" "Label31" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ff3030} -font font10 -foreground {#000000} \
        -highlightcolor black -text {Not recording to local disk} \
        -textvariable recordingState 
    vTcl:DefineAlias "$top.lab43" "Label32" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo35 \
        -in $top -x 10 -y 70 -width 602 -height 474 -anchor nw \
        -bordermode ignore 
    place $top.lab42 \
        -in $top -x 140 -y 10 -width 335 -height 19 -anchor nw \
        -bordermode ignore 
    place $top.lab43 \
        -in $top -x 140 -y 40 -width 333 -height 19 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top34

